version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "daily"
