version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all-dependencies"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "all-dependencies"

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
