# Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Trivy (Published Images)
on:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read
  security-events: write
  id-token: write
  
jobs:
  trivy-published:
    if: ${{ github.repository == 'aws/csi-components' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::702945799511:role/github-actions-csi-components
          role-session-name: GithubActionsTrivy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::797935246662:role/github-actions-csi-components
          role-session-name: GithubActionsTrivy

      # We use the staging repo because it ensures the images are always available (even while a
      # release is ongoing) and we expect it to be bit for bit identical to the published images
      # 
      # This also allows us to easily scan all images in a single place as some images (e.g.
      # the volume-modifier-for-k8s image) are promoted to separate registries
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1

      - name: Run Trivy (SARIF Output)
        env:
          OUTPUT_SARIF: 'true'
        run: make all-trivy

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: output/
